# Generated by Django 3.0.6 on 2020-05-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clave',
            field=models.CharField(max_length=3, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dpi',
            field=models.CharField(max_length=13, verbose_name='DPI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=9, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tarjeta',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(max_length=8, verbose_name='Teléfono'),
        ),
    ]
