# Generated by Django 3.0.6 on 2020-05-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0002_auto_20200513_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=8, verbose_name='Teléfono'),
        ),
    ]
