# Generated by Django 3.0.6 on 2020-05-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0003_auto_20200513_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clave',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
