# Generated by Django 3.0.6 on 2020-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0004_auto_20200517_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba', models.CharField(max_length=10)),
            ],
        ),
    ]
