# Generated by Django 3.0.6 on 2020-05-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0005_pueba'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pueba',
            new_name='Prueba',
        ),
    ]
