# Generated by Django 3.0.6 on 2020-05-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0006_auto_20200518_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='prueba',
            field=models.IntegerField(),
        ),
    ]
