# Generated by Django 3.0.6 on 2020-05-20 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0007_auto_20200518_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='prueba',
            new_name='prueba1',
        ),
        migrations.AddField(
            model_name='prueba',
            name='prueba2',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
