# Generated by Django 3.0.6 on 2020-05-20 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0008_auto_20200519_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='prueba3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
