# Generated by Django 3.0.6 on 2020-05-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0009_prueba_prueba3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dpi',
            field=models.CharField(max_length=13, unique=True, verbose_name='DPI'),
        ),
    ]
