# Generated by Django 3.0.6 on 2020-05-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0010_auto_20200522_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('nit', models.CharField(max_length=9)),
            ],
        ),
    ]
