# Generated by Django 3.0.6 on 2020-05-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0011_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('Escritorio', (('nuevas', 'Nuevas'), ('semi nuevas', 'Semi Nuevas'), ('gaming', 'Gaming'), ('todo_uno', 'Todo en uno'), ('oficina', 'Oficina'))), ('NoteBook', (('nuevas', 'Nuevas'), ('semi nuevas', 'Semi Nuevas'), ('gaming', 'Gaming'), ('ultrabook', 'UltraBook'), ('pulgadas', 'Pulgadas (13",15",16.5")'))), ('Componentes', (('teclados', 'Teclados'), ('mouse', 'Mouse'), ('tarjetas_graficas', 'Tarjetas Graficas'), ('tarjetas_ram', 'Tarjetas Ram'), ('tarjeta_ethernet', 'Tarjeta Ethernet'), ('monitores', 'Monitores'), ('kit_de_limpieza_y_mantenimiento', 'Kit de limpieza de mantenimiento'), ('case', 'Case'), ('procesadores', 'Procesadores'), ('motherboard', 'Motherboard'), ('ventiladores', 'Ventiladores'), ('fuente_de_alimentacion', 'Fuente de alimentacion'), ('bocinas', 'Bocinas'), ('discos_duro', 'Discos duro'), ('disco_estado_solido', 'Disco estado solido'), ('web_cam', 'Web Cam'), ('memorias_usb', 'Memorias USB'), ('lector_de_cd', 'Lector de sD'), ('cd_room', 'CD-ROM'), ('impresoras', 'Impresoras'), ('bandas_ide_y_sata', 'Bandas IDE y SATA')))], default='NoteBook', max_length=35)),
                ('unidades', models.IntegerField()),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_total_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('foto_producto', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=500)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaEquipo.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroVenta', models.IntegerField(verbose_name='No. Venta')),
                ('pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], max_length=9)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cantidad', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaEquipo.Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaEquipo.Producto')),
            ],
        ),
    ]
