# Generated by Django 3.0.6 on 2020-05-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0012_producto_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numeroVenta',
            field=models.IntegerField(unique=True, verbose_name='No. Venta'),
        ),
    ]
