# Generated by Django 3.0.6 on 2020-05-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0017_auto_20200524_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
