# Generated by Django 3.0.6 on 2020-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0019_auto_20200524_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Escritorio', (('nuevas', 'Nuevas'), ('semi nuevas', 'Semi Nuevas'), ('gaming', 'Gaming'), ('todo_uno', 'Todo en uno'), ('oficina', 'Oficina'))), ('NoteBook', (('nuevas', 'Nuevas'), ('semi nuevas', 'Semi Nuevas'), ('gaming', 'Gaming'), ('ultrabook', 'UltraBook'), ('pulgadas', 'Pulgadas (13",15",16.5")'))), ('Componentes', (('teclados', 'Teclados'), ('mouse', 'Mouse'), ('tarjetas_graficas', 'Tarjetas Graficas'), ('tarjetas_ram', 'Tarjetas Ram'), ('tarjeta_ethernet', 'Tarjeta Ethernet'), ('monitores', 'Monitores'), ('kit_de_limpieza_y_mantenimiento', 'Kit de limpieza de mantenimiento'), ('case', 'Case'), ('procesadores', 'Procesadores'), ('motherboard', 'Motherboard'), ('ventiladores', 'Ventiladores'), ('fuente_de_alimentacion', 'Fuente de alimentacion'), ('bocinas', 'Bocinas'), ('discos_duro', 'Discos duro'), ('disco_estado_solido', 'Disco estado solido'), ('web_cam', 'Web Cam'), ('memorias_usb', 'Memorias USB'), ('lector_de_cd', 'Lector de sD'), ('cd_room', 'CD-ROM'), ('impresoras', 'Impresoras'), ('bandas_ide_y_sata', 'Bandas IDE y SATA')))], default='NoteBook', max_length=35, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=50, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_total_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=45, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(max_length=9, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
    ]
