# Generated by Django 3.0.6 on 2020-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0020_auto_20200525_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(upload_to='productos', verbose_name='Foto'),
        ),
    ]
