# Generated by Django 3.0.6 on 2020-05-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0021_auto_20200525_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=8),
            preserve_default=False,
        ),
    ]
