# Generated by Django 3.0.6 on 2020-05-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0022_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Escritorio', (('nuevas', 'Nuevas'), ('semi nuevas', 'Semi Nuevas'), ('gaming', 'Gaming'), ('todo_uno', 'Todo en uno'), ('oficina', 'Oficina'))), ('NoteBook', (('nuevas', 'Nuevas'), ('semi nuevas', 'Semi Nuevas'), ('gaming', 'Gaming'), ('ultrabook', 'UltraBook'), ('pulgadas', 'Pulgadas (13",15",16.5")'))), ('Componentes', (('teclados', 'Teclados'), ('mouse', 'Mouse'), ('tarjetas_graficas', 'Tarjetas Graficas'), ('tarjetas_ram', 'Tarjetas Ram'), ('tarjeta_ethernet', 'Tarjeta Ethernet'), ('monitores', 'Monitores'), ('kit_de_limpieza_y_mantenimiento', 'Kit de limpieza de mantenimiento'), ('case', 'Case'), ('procesadores', 'Procesadores'), ('motherboard', 'Motherboard'), ('ventiladores', 'Ventiladores'), ('fuente_de_alimentacion', 'Fuente de alimentacion'), ('bocinas', 'Bocinas'), ('discos_duro', 'Discos duro'), ('disco_estado_solido', 'Disco estado solido'), ('web_cam', 'Web Cam'), ('memorias_usb', 'Memorias USB'), ('lector_de_cd', 'Lector de sD'), ('cd_room', 'CD-ROM'), ('impresoras', 'Impresoras'), ('bandas_ide_y_sata', 'Bandas IDE y SATA')))], max_length=35, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_total_compra',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de Venta'),
        ),
    ]
