# Generated by Django 3.0.6 on 2020-05-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0023_auto_20200525_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaEquipo.Cliente')),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaEquipo.Venta')),
            ],
        ),
    ]
