# Generated by Django 3.0.6 on 2020-05-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0024_factura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
