# Generated by Django 3.0.6 on 2020-05-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaEquipo', '0025_delete_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
